/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'twcn' at '9/23/16 10:39 AM' with Gradle 3.1
 *
 * @author twcn, @date 9/23/16 10:39 AM
 */
public class Exercise {
    public static void main(String[] args) {
        long time = System.currentTimeMillis();
//        System.out.print(time);
        double money = 3.0;
        double price = 2.9;
//        System.out.print(money - price);        //0.10000000000000009
        char c1 = '中';
        char c2 = '\u4e2d';
//        System.out.print(c1);
//        System.out.print(c2);
        boolean isChild = 16 < 18;
//        System.out.print(isChild);
        long l1 = 1024l;
        int i = (int)l1;
//        System.out.print(i);
        long l2 = 1024l * 1024 * 1024 * 4;
        int j = (int)l2;
        System.out.print(j);      //0, 溢出
        double pi = 3.141592612345678923456;
        float f = (float)pi;
        System.out.print(f);       //3.1415925 精度丧失
        byte b1 = 5;
        byte b2 = 6;
        byte b3 = (byte)(b1 + b2);

    }
}
